### ISSUE TITLE
I can't get docker miele-to-mqtt-gw to work

### ISSUE THREAD

**Issue by cvc90** [mqtt-home/miele-to-mqtt-gw#106] opened 2023-05-30 12:54 UTC
Hello, could you help me to get  [miele-to-mqtt-gw](https://github.com/mqtt-home/miele-to-mqtt-gw)? For some reason I can't get the Docker version to work, it doesn't get the token to work and looking at the log it gives me a 401 error (invalid credentials) and that's why it doesn't receive the token (I attach an image showing what I'm saying).

![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/0edf296e-d3d5-4070-9687-a27147b41a8d)
![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/addbcf6d-265e-40fb-9c17-8961e8fc7525)

The configuration is the same as [config-example.json]( https://github.com/mqtt-home/miele-to-mqtt-gw/blob/main/config-example.json) but changing client-id, client -secret, username, password and I checked the credentials both on the page and in the miele app and I can say that it works correctly.

From the page https://www.miele.com/developer/swagger-ui/swagger.html everything seems to work correctly and I can see my devices without problems.

![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/2a0d1cdc-69db-44cc-b65e-8a60c731becd)

Could it be that today [miele-to-mqtt-gw](https://github.com/mqtt-home/miele-to-mqtt-gw) doesn't work?
or the credentials written in the .json file containing special characters do not read them correctly?

**Comment by AleksCee** [comment] 2023-05-30 14:38
Hi @cvc90 in my log are errors since 1 am today but I have just restart the container and it‘s seams to work right now:

16:33:02.609 INFO  - Info enabled
16:33:02.627 INFO  - Connecting MQTT client
16:33:04.159 INFO  - MQTT client connected
16:33:06.582 INFO  - Using Miele polling api

Alex

**Comment by philipparndt** [comment] 2023-05-30 15:12
@cvc90 which version do you use? Do you like to test `pharndt/mielemqtt:3.0.0-pre`?

my full config.json:
```json
{
  "mqtt": {
    "url": "tcp://mosquitto:1883",
    "retain": true,
    "topic": "home/miele",
    "qos": 2,
    "bridge-info": true,
    "autoPublish": true,
    "deduplicate": true
  },
  "miele": {
    "client-id": "12345678-abcd-1234-1234-123456789abc",
    "client-secret": "01234567890123456789012345678901",
    "username": "some@other.de",
    "password": "password",
    "mode": "sse",
    "polling-interval": 30,
    "token": {
      "access": "DE_5c...",
      "refresh": "DE_f6...",
      "validUntil": "2022-08-30T11:32:40.434+02:00[Europe/Berlin]"
    }
  }
}
```

my docker-compose.yml snipped
```yml
  ...
  mielemqtt:
    environment:
      TZ: "Europe/Berlin"
    hostname: mielemqtt
    image: pharndt/mielemqtt:3.0.0-pre
    volumes:
      - ./config/miele:/var/lib/miele-to-mqtt-gw:rw
    restart: always
    depends_on:
      - mosquitto
    cpus: 0.1
    mem_reservation: "50M"
    mem_limit: "50M"
  ...
```

**Comment by cvc90** [comment] 2023-05-30 16:07
I have updated the docker to version pharndt/mielemqtt:3.0.0-pre, now the same error appears but with another explanation, I attach an image with the current error.

![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/e8078b30-463a-4618-a589-1e7f63bc2c0c)

**Comment by cvc90** [comment] 2023-05-31 18:45
Hello, I updated the docker to version "pharndt/mielemqtt:3.0.1-pre" using the configuration from [config-example.json](https://github.com/mqtt-home/miele-to-mqtt- gw/blob/main/config-example.json) but changing the client id, client-secret, username, password, I can say that it doesn't work as I show in the photo, it keeps giving error 401 without authorization.

![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/bae9ecbe-d462-4319-8d07-c7d72a138796)

Using the configuration that you comment and accessing [Miele Developer](https://www.miele.com/developer/swagger-ui/swagger.html) to get the access_token and refresh_token (Thanks to Chrome development mode seeing the request ) I can say that it works correctly as I show in the photo.

![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/b3a2fe1e-c806-45d7-9711-4e4c3047025f)


@philipparndt Thanks for getting it to work!! 💯 🚀

**Comment by philipparndt** [comment] 2023-06-01 15:48
@cvc90 I think I have found the root cause for the problem. The country-code was hard-coded to `de-DE`.

Can you test this version: `pharndt/mielemqtt:3.1.0`

With this config (based on your GitHub profile I guess the country code could `es-ES` :wink:):

```json
{
  ...
  "miele": {
    "client-id": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    "client-secret": "12345678901234567890123456789012",
    "polling-interval": 30,
    "username": "miele_at_home_user@example.com",
    "password": "miele_at_home_password",
    "country-code": "es-ES",
    "mode": "sse"
  }
}
```

**Comment by philipparndt** [comment] 2023-06-02 13:56
- The error message is addressed in `pharndt/mielemqtt:3.1.1`
- The logging will now respect the TZ setting from the docker container
- It is possible to set the log level again

I do not plan to provide other languages in error messages, as this is hard to maintain. Nevertheless, thank you for the offer to help 😄.

Thanks for the hint with the wrong position of the country code in the documentation 👍.

**Comment by cvc90** [comment] 2023-06-02 18:59
Hi! I just updated Docker to version pharndt/mielemqtt:3.1.1 and these are my impressions after trying it.

- Log messages now showing without having the token in the .json file have been removed and no longer show the error.

- The container correctly collects the "TZ" variable as shown in the attached image correctly shows the date and time. Although the displayed date format is YYYY/MM/DD and the correct format would be DD/MM/YYYY.

- I have added the new variable "loglevel": "info" and "loglevel": "debug" to the .json file and everything seems to work correctly.

![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/90662265-5f23-405c-85ac-90a05680b19e)
![image](https://github.com/mqtt-home/miele-to-mqtt-gw/assets/76731844/7abf7226-cc46-46ee-ae3c-d197445cd188)

**Comment by cvc90** [comment] 2023-06-08 17:08
Would it be possible to add the MQTT autodiscovery option? I can't sync with Home Assistant, but I see the topic "miele" from MQTT Explorer.

**Comment by philipparndt** [comment] 2023-06-10 06:58
> Would it be possible to add the MQTT autodiscovery option? I can't sync with Home Assistant/Domoticz, but I see the topic "miele" from MQTT Explorer.

@cvc90 I add this to an separate issue: https://github.com/mqtt-home/miele-to-mqtt-gw/issues/136

**Closed by philipparndt** 2023-06-10 06:58 UTC
